### PR TITLE
Use GCC

### PR DESCRIPTION
**Pull request by CloudedQuartz**
Use GCC and fix all associated warnings/errors

### CODE REVIEW

**Review by sajidshahriar72543 — COMMENTED** [review]
Pro af

**Comment by CloudedQuartz** [comment]
> Pro af

Nou

**Review by humanglitch191 — APPROVED** [review]

**Review by PainKiller3 — APPROVED** [review]

**Review by mukul2259 — APPROVED** [review]
Seems fine to me.

**Review by neel685 — APPROVED** [review]
looks fine to me too

**Pull request merged**
